### ISSUE TITLE
Empty argument not quoted correctly

### ISSUE THREAD

**Issue by avdv** [ljharb/shell-quote#18]
```js
> var quote = require('shell-quote/quote');
> quote([ 'x', '', 'x' ]);
'x  x'
```
ie. passing in 3 arguments, we only get 2 out as the empty arg does not get any treatment.

The correct output would be `x '' x`.

**Comment by ljharb** [comment]
Indeed, given that `parse('-x "" y')` is `[ '-x', '', 'y' ]`, it seems like a clear bug that `quote([ '-x', '', 'y' ])` is not `[ '-x', '', 'y' ]`.
