### ISSUE TITLE
Whitespace in comments gets mangled and sometimes deleted

### ISSUE THREAD

**Issue by haltman-at** [ljharb/shell-quote#6]
If I do `parse("#abc  def  ghi")`, instead of `[{ comment: "abc  def  ghi" }]`, the result is `[{ comment: "abcdef ghi" }]`.

(Tested with shell-quote version 1.8.0.)

**Comment by ljharb** [comment]
This seems pretty expected on a shell - multiple space separators get collapsed into one, i think? or are you saying because it's a comment you expect them to be preserved?

**Comment by haltman-at** [comment]
Yeah, I would expect the `comment` field to contain the exact text of the comment.  Like there shouldn't be any parsing being applied to the text of a comment!
